/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazCompilador;

import LogicaCompilador.*;
import java.util.ArrayList;

import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author unityofdisaster
 */
public class VentanaConvertir extends javax.swing.JFrame {

    /**
     * Creates new form convertirAFN
     */
    HashMap<String, AFN> listaAFN;
    HashMap<String, AFD> listaAFD;

    public VentanaConvertir(HashMap<String, AFN> listaAFN, HashMap<String, AFD> listaAFD) {

        this.listaAFN = listaAFN;
        this.listaAFD = listaAFD;
        initComponents();
        boxAFN.removeAllItems();
        String[] aux = new String[this.listaAFN.size()];
        int contador = 0;
        for (String k : this.listaAFN.keySet()) {
            aux[contador] = k;
            contador++;
        }
        boxAFN.setModel(new javax.swing.DefaultComboBoxModel<>(aux));

        contador = 0;
        aux = new String[this.listaAFD.size()];
        boxAFD.removeAllItems();
        for (String k : this.listaAFD.keySet()) {
            aux[contador] = k;
            contador++;
        }
        boxAFD.setModel(new javax.swing.DefaultComboBoxModel<>(aux));

        jLabel2.setVisible(true);
        botonConvertir.setVisible(true);
        boxAFN.setVisible(true);

        jLabel4.setVisible(false);
        botonMostrar.setVisible(false);
        boxAFD.setVisible(false);
        this.botonConvertir.setName("botonConvertir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonConvertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxAFN = new javax.swing.JComboBox<>();
        boxOpciones = new javax.swing.JComboBox<>();
        boxAFD = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        botonConvertir.setText("Convertir");
        botonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConvertirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Convertir AFN a AFD");

        jLabel2.setText("Seleccionar AFN");

        boxAFN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAFNActionPerformed(evt);
            }
        });

        boxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Convertir AFN", "Mostrar Tabla" }));
        boxOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxOpcionesActionPerformed(evt);
            }
        });

        boxAFD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAFDActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione opcion");

        jLabel4.setText("Seleccione AFD");

        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boxAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(boxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(207, 207, 207)
                                    .addComponent(jLabel4))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(jLabel1))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxAFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxAFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConvertir)
                    .addComponent(botonMostrar))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConvertirActionPerformed
        if (this.listaAFN.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Aun no existen automatas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            AFN obj1 = this.listaAFN.get(boxAFN.getItemAt(boxAFN.getSelectedIndex()));
            AFD obj2 = new AFD();
            obj2.convertirAFN(obj1);
            this.listaAFD.put("afd" + (this.listaAFD.size() + 1), obj2);

            llenarTabla(obj2.tabla(), obj2.getAlfabetoOrdenado());
        }
    }//GEN-LAST:event_botonConvertirActionPerformed

    public void llenarTabla(ArrayList<ArrayList<Integer>> datos, ArrayList<Character> letras) {
        Object[][] modeloTabla = new Object[datos.size()][datos.get(0).size()];
        Iterator it;
        int f = 0, c = 0;
        int numero;
        //se recorren filas y columnas del arraylist
        for (ArrayList filas : datos) {
            it = filas.iterator();
            while (it.hasNext()) {
                numero = (Integer) it.next();
                modeloTabla[f][c] = (Object)numero;
                c++;
            }
            c = 0;
            f++;
            System.out.println("");
        }
        //(a|b)+c*
        //String[] col = {"Clave Articulo","Nombre Articulo","Descripcion Articulo","precio","existencia"};
        String[] cols = new String[letras.size() + 3];
        cols[0] = "edo";
        int i = 1;
        for (Character s : letras) {
            cols[i] = s.toString();
            i++;
        }
        cols[i++] = "acept";
        cols[i] = "tk";
        jTable1.setModel(
                new javax.swing.table.DefaultTableModel(modeloTabla, cols));
    }
    private void boxAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAFNActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        if (this.listaAFD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Aun no existen automatas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            AFD obj;
            obj = this.listaAFD.get(boxAFD.getItemAt(boxAFD.getSelectedIndex()));
            llenarTabla(obj.tabla(), obj.getAlfabetoOrdenado());
        }
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void boxAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAFDActionPerformed

    private void boxOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxOpcionesActionPerformed
        switch (boxOpciones.getSelectedIndex()) {
            case 0:
                jLabel2.setVisible(true);
                botonConvertir.setVisible(true);
                boxAFN.setVisible(true);

                jLabel4.setVisible(false);
                botonMostrar.setVisible(false);
                boxAFD.setVisible(false);
                break;
            case 1:
                jLabel2.setVisible(false);
                botonConvertir.setVisible(false);
                boxAFN.setVisible(false);

                jLabel4.setVisible(true);
                botonMostrar.setVisible(true);
                boxAFD.setVisible(true);
                int contador = 0;
                String[] aux = new String[this.listaAFD.size()];
                boxAFD.removeAllItems();
                for (String k : this.listaAFD.keySet()) {
                    aux[contador] = k;
                    contador++;
                }
                boxAFD.setModel(new javax.swing.DefaultComboBoxModel<>(aux));

                break;
        }
    }//GEN-LAST:event_boxOpcionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConvertir;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JComboBox<String> boxAFD;
    private javax.swing.JComboBox<String> boxAFN;
    private javax.swing.JComboBox<String> boxOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
