/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazCompilador;

import java.util.ArrayList;
import java.util.Arrays;
import LogicaCompilador.*;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;




/**
 *
 * @author sandu
 */
public class VentanaAnalisisLexico extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAnalisisLexico
     */
    HashMap<String, AFN> listaAFN;

    public VentanaAnalisisLexico(HashMap<String, AFN> listaAFN) {
        this.listaAFN = listaAFN;
        initComponents();
        String[] aux = new String[this.listaAFN.size()];
        int contador = 0;
        for (String k : this.listaAFN.keySet()) {
            aux[contador] = k;
            contador++;
        }
        Arrays.sort(aux);

        listaAutomatas.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() {
                return aux.length;
            }

            public String getElementAt(int i) {
                return aux[i];
            }
        });
        jScrollPane1.setViewportView(listaAutomatas);
        this.botonUnir.setName("botonUnir");
        this.listaAutomatas.setName("listaAutomatas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAutomatas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        botonUnir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Unir para analisis lexico");

        listaAutomatas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaAutomatas);

        jLabel2.setText("Seleccione los automatas que se uniran");

        botonUnir.setText("Unir seleccionados");
        botonUnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonUnir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(botonUnir)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonUnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnirActionPerformed
        int[] indices = this.listaAutomatas.getSelectedIndices();
        if (indices.length == 0) {
            JOptionPane.showMessageDialog(null, "Aun no existen automatas o no ha seleccionado mas de uno", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<AFN> automatas = new ArrayList<AFN>();
            List<String> valores = this.listaAutomatas.getSelectedValuesList();
            AFN obj1 = null;
            int contador = 0;
            for (String i : valores) {
                if (contador == 0) {
                    obj1 = this.listaAFN.get(i);
                } else {
                    automatas.add(this.listaAFN.get(i));
                    this.listaAFN.remove(i);
                }
                contador++;
            }
            obj1.unirAL(automatas);

            /////////////////////
            String[] aux = new String[this.listaAFN.size()];
            contador = 0;
            for (String k : this.listaAFN.keySet()) {
                aux[contador] = k;
                contador++;
            }
            Arrays.sort(aux);
            listaAutomatas.setModel(new javax.swing.AbstractListModel<String>() {
                public int getSize() {
                    return aux.length;
                }

                public String getElementAt(int i) {
                    return aux[i];
                }
            });
            jScrollPane1.setViewportView(listaAutomatas);

            ////////////////////
        }
    }//GEN-LAST:event_botonUnirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonUnir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaAutomatas;
    // End of variables declaration//GEN-END:variables
}
