/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazCompilador;

import java.util.HashMap;
import LogicaCompilador.*;
import java.util.ArrayList;
import javafx.util.Pair;
import javax.swing.JOptionPane;

/**
 *
 * @author unityofdisaster
 */
public class VentanaValidacion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaValidacion
     */
    private HashMap<String, AFD> deterministas;

    public VentanaValidacion(HashMap<String, AFD> deterministas) {
        this.deterministas = deterministas;
        initComponents();
        String[] aux = new String[this.deterministas.size()];
        int contador = 0;
        for (String k : this.deterministas.keySet()) {
            aux[contador] = k;
            contador++;
        }
        boxAFD.setModel(new javax.swing.DefaultComboBoxModel<>(aux));
        this.botonValidar.setName("botonValidar");
        this.campoCadena.setName("campoCadena");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxAFD = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        campoCadena = new javax.swing.JTextField();
        botonValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Validacion de cadenas");

        jLabel3.setText("Seleccione AFD");

        boxAFD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Ingrese cadena");

        campoCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCadenaActionPerformed(evt);
            }
        });

        botonValidar.setText("Validar");
        botonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel3)))
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(botonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(boxAFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonValidar)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCadenaActionPerformed

    private void botonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValidarActionPerformed
        if (this.deterministas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Aun no existen automatas", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String cadena = campoCadena.getText();
            AFD obj1;
            obj1 = this.deterministas.get(this.boxAFD.getItemAt(this.boxAFD.getSelectedIndex()));
            AnalizadorLexico lex = new AnalizadorLexico(obj1);
            lex.setCadena(cadena);
            int tk = 0;
            Object [][] modeloTabla;
            ArrayList<Pair<String,String>> pares = new ArrayList<Pair<String,String>>();
            while(tk != 1000){
                tk = lex.getToken();
                if(tk !=1000){
                    pares.add(new Pair(Integer.toString(tk),lex.getLexema()));
                    System.out.println("Token: "+tk+" Lexema: "+lex.getLexema());
                }
            }
            modeloTabla = new Object[pares.size()][2];
            int i = 0;
            for(Pair a: pares){
                modeloTabla[i][0] = (Object)a.getKey();
                modeloTabla[i][1] = (Object)a.getValue();
                i++;
            }
            String[] cols = new String[2];
            cols[0] = "tokens";
            cols[1] ="lexemas";
            jTable1.setModel( new javax.swing.table.DefaultTableModel(modeloTabla, cols));
            if(lex.cadena(cadena)){
                JOptionPane.showMessageDialog(null, "Cadena Pertenece al lenguaje", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Cadena no pertenece al lenguaje", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonValidarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonValidar;
    private javax.swing.JComboBox<String> boxAFD;
    private javax.swing.JTextField campoCadena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
