/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazCompilador;

import LogicaCompilador.AnalizadorLexico;
import LogicaCompilador.Calculadora;
import LogicaCompilador.AFD;
import LogicaCompilador.AFN;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.*;

/**
 *
 * @author sandu
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCalculadora
     */
    private AnalizadorLexico lex;
    private Calculadora calc;
    private boolean exists;
    public VentanaCalculadora() {
        exists = false;
        calc = null;
        lex = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReglas = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        expresion = new javax.swing.JTextField();
        btnEvaluar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReglas.setText("Generar reglas");
        btnReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReglasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora básica");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Evaluar expresión");

        expresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expresionActionPerformed(evt);
            }
        });

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Resultado");

        resultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expresion)
                            .addComponent(btnReglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEvaluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31))
                            .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReglas)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(expresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEvaluar)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private AnalizadorLexico generarReglas(){
        AFN a = new AFN(); //se crea un AFN
        AFN b = new AFN(); //se crea un AFN
        AFN c = new AFN(); //se crea un AFN
        AFN d = new AFN(); //se crea un AFN

        AFN token10 = new AFN();
        AFN token20 = new AFN();
        AFN token30 = new AFN();
        AFN token40 = new AFN();
        AFN token50 = new AFN();
        AFN token60 = new AFN();
        AFN token70 = new AFN();
        token10.basico('+');
        token10.setToken(10);
        token20.basico('-');
        token20.setToken(20);
        token30.basico('*');
        token30.setToken(30);
        token40.basico('/');
        token40.setToken(40);
        token50.basico('(');
        token50.setToken(50);
        token60.basico(')');
        token60.setToken(60);



        token70 = new AFN();
        token70.basico('0');
        a = new AFN();
        a.basico('1');
        token70.unir(a);
        a = new AFN();
        a.basico('2');
        token70.unir(a);
        a = new AFN();
        a.basico('3');
        token70.unir(a);
        a = new AFN();
        a.basico('4');
        token70.unir(a);
        a = new AFN();
        a.basico('5');
        token70.unir(a);
        a = new AFN();
        a.basico('6');
        token70.unir(a);
        a = new AFN();
        a.basico('7');
        token70.unir(a);
        a = new AFN();
        a.basico('8');
        token70.unir(a);
        a = new AFN();
        a.basico('9');
        token70.unir(a);
        token70.cerraduraPositiva();

        
        AFN punto = new AFN();
        punto.basico('.');

        AFN num1 = new AFN();
        num1.basico('0');
        a = new AFN();
        a.basico('1');
        num1.unir(a);
        a = new AFN();
        a.basico('2');
        num1.unir(a);
        a = new AFN();
        a.basico('3');
        num1.unir(a);
        a = new AFN();
        a.basico('4');
        num1.unir(a);
        a = new AFN();
        a.basico('5');
        num1.unir(a);
        a = new AFN();
        a.basico('6');
        num1.unir(a);
        a = new AFN();
        a.basico('7');
        num1.unir(a);
        a = new AFN();
        a.basico('8');
        num1.unir(a);
        a = new AFN();
        a.basico('9');
        num1.unir(a);
        num1.cerraduraPositiva();

        punto.concatenar(num1);
        punto.Question();

        token70.concatenar(punto);
        token70.setToken(70);

        //unirlos
        ArrayList<AFN> automatas = new ArrayList<AFN>();
        automatas.add(token10);
        automatas.add(token20);
        automatas.add(token30);
        automatas.add(token40);
        automatas.add(token50);
        automatas.add(token60);
        automatas.add(token70);


        token10.unirAL(automatas);
        token10.imprimirTransicionesAFN();
//prueba del maestro para entregar GG

        //convertir a AFD
        AFD n = new AFD();
        n.convertirAFN(token10);
        int numeroInicial=token10.getInicial().getIdentificador();

        System.out.println("----------------------------------------");
        n.imprimirTransicionesAFD();

        ArrayList<ArrayList<Integer>> tabla = n.tabla();
        ArrayList<Character> alfabetoOrdenado = n.getAlfabetoOrdenado();
        System.out.println("----------------------------------------");
        System.out.print("E\t");

        for(int i=0;i<alfabetoOrdenado.size();i++){
            System.out.print(alfabetoOrdenado.get(i)+"\t");
        }
        System.out.println("A\tT");
        for(int i=0;i< tabla.size();i++){ //por cada fila
            for(int j = 0; j < n.getAlfabeto().size()+3;j++){ //por cada caracter + 3 (estado inicial token y final)
                if(j<n.getAlfabeto().size()+1 && tabla.get(i).get(j)!=-1){
                    System.out.print((tabla.get(i).get(j))+"\t");
                }
                else{
                    System.out.print(tabla.get(i).get(j)+"\t");
                }
            }
            System.out.println();
        }

       

        //para probar una cadena
        
        AnalizadorLexico al = new AnalizadorLexico();
        al.setAFD(n);
        return al;
    }
    
    
    private void btnReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReglasActionPerformed
        if(exists){
            JOptionPane.showMessageDialog(null, "Ya se generaron las reglas", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }else{
            this.lex = generarReglas();
            this.calc = new Calculadora(lex);
            JOptionPane.showMessageDialog(null, "Se han creado reglas de forma exitosa","Correcto",JOptionPane.INFORMATION_MESSAGE);
            exists=true;
        }
        
        
    }//GEN-LAST:event_btnReglasActionPerformed

    private void expresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expresionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expresionActionPerformed

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        String cadena = this.expresion.getText();
        if (cadena.equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese una cadena valida","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            float res;
            this.lex.setCadena(cadena);
            res = this.calc.Evaluar();
            if(res == -1f){
                this.resultado.setText("expresion invalida");
            }else{
                this.resultado.setText(Float.toString(res));
            }
        }
    }//GEN-LAST:event_btnEvaluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEvaluar;
    private javax.swing.JToggleButton btnReglas;
    private javax.swing.JTextField expresion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
