/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazCompilador;

import LogicaCompilador.*;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author sandu
 */
public class VentanaCreaAFN extends javax.swing.JFrame {

    /**
     * Creates new form CreaAFN
     */
    private HashMap<String, AFN> lista;

    public VentanaCreaAFN() {
        initComponents();
        this.crearAFN.setName("crearAFN");
        this.nombreAFN.setName("nombreAFN");
    }    
    public VentanaCreaAFN(HashMap<String, AFN> automatas) {
        this.lista = automatas;
        initComponents();
        this.crearAFN.setName("crearAFN");
        this.nombreAFN.setName("nombreAFN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearAFN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombreAFN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel1.setText("Crear AFN");

        crearAFN.setText("Crear");
        crearAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAFNActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese nombre de AFN");

        nombreAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAFNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crearAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(nombreAFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crearAFN)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAFNActionPerformed
        String cadena = nombreAFN.getText();
        if (!cadena.equals("")) {
            if (this.lista.containsKey(cadena)) {
                JOptionPane.showMessageDialog(null, "Ya existe un automata con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (cadena.contains(",")) {
                    String aux = "";
                    for (String s : cadena.split("")) {
                        if (s.equals(",")) {
                            this.lista.put(aux, new AFN());
                            aux = "";
                        } else {
                            aux += s;
                        }
                    }
                    this.lista.put(aux, new AFN());
                } else {
                    this.lista.put(cadena, new AFN());
                }
               // JOptionPane.showMessageDialog(null, "Se ha agregado " + cadena + " correctamente", "Correcto",
               //         JOptionPane.INFORMATION_MESSAGE);
            }
            this.nombreAFN.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un nombre para el automata", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearAFNActionPerformed

    private void nombreAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAFNActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearAFN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombreAFN;
    // End of variables declaration//GEN-END:variables
}
